[programs.localnet]
sandbox = "DLjexKmTr6f9ZqLnYzvEVWzfH7b6dpFPjgdn5P7t2UeM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/danmt/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
